logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  false
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

rpcServer:
  serverName: "authorize"
  registerPlugin: "etcd"
  registerServers:
    - "192.168.101.24:2379"
  basePath: "go-admin-example"
  addr: ""
  port: 8899
  pprof: 18899

db:
  dbType: "mysql"
  maxOpenConn: 20
  maxIdleConn: 4
  maxIdleTime: 100
  maxLifeTime: 3600
  level: 4
  slowThreshold: "100ms"
  master:
    user: "root"
    password: "123456"
    host: "192.168.101.24"
    port: "3306"
    database: "go-admin"
  slave:
    - user: "root"
      password: "123456"
      host: "192.168.101.24"
      port: "3306"
      database: "go-admin"

redis:
  redisType: "cluster"
  startAddr: ["192.168.101.24:7001","192.168.101.24:7002","192.168.101.24:7003","192.168.101.24:7004","192.168.101.24:7005","192.168.101.24:7006"]
  active: 100
  idle: 100
  auth: ""
  connTimeout: "100ms"
  readTimeout: "100ms"
  writeTimeout: "100ms"
  idleTimeout: "100ms"

tracer:
  openTrace: false
  traceName: "authorize"
  host: "127.0.0.1:6831"

captcha:
  length: 6
  strType: 3
  bkgColors:
    - B: 255
      A: 255

jwt:
  model: "unique"
  key: "go-admin-example-123456"
  expireTime: 60*60*24

analysisServer:
  type: "rpc"
  port: 8999
  serviceName: "authorize"
  prometheus: true
